name: desktop_webview_linux
description: "Webview on Linux using webkit2gtk. desktop_webview_window only Linux part."
version: 0.1.1
repository: https://github.com/Carapacik/desktop_webview_linux
topics:
  - webview
  - linux
  - webkit2gtk
  - webkitgtk
environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1

dev_dependencies:
  carapacik_lints: ^1.12.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: DesktopWebviewLinuxPlugin
